# Generated by Django 2.2 on 2019-04-08 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveGames',
            fields=[
                ('game_ID', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('char_class', models.CharField(max_length=20)),
                ('char_name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=99999)),
                ('charm', models.IntegerField()),
                ('cool', models.IntegerField()),
                ('sharp', models.IntegerField()),
                ('tough', models.IntegerField()),
                ('weird', models.IntegerField()),
                ('luck', models.IntegerField()),
                ('harm', models.IntegerField()),
                ('experience', models.IntegerField()),
                ('move_list', models.CharField(max_length=100)),
                ('weapon_list', models.CharField(max_length=100)),
                ('improvements_list', models.CharField(max_length=100)),
                ('advImprovements_list', models.CharField(max_length=100)),
                ('char_specific', models.CharField(max_length=100)),
            ],
            options={
                'unique_together': {('game_ID', 'char_class')},
            },
        ),
        migrations.CreateModel(
            name='AdvImprovements',
            fields=[
                ('improvement_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('char_class', models.CharField(max_length=20)),
                ('improvement', models.CharField(max_length=100)),
            ],
            options={
                'unique_together': {('improvement_ID', 'char_class')},
            },
        ),
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('agency_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('resource', models.BooleanField()),
                ('red_tape', models.BooleanField()),
                ('option', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='AssignedGear',
            fields=[
                ('char_class', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('gear_ID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DarkSide',
            fields=[
                ('tag_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('tag', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Fate',
            fields=[
                ('fate_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('heroic', models.BooleanField()),
                ('doom', models.BooleanField()),
                ('fate_tag', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Gear',
            fields=[
                ('gear_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('weapon_name', models.CharField(max_length=20)),
                ('damage', models.IntegerField()),
                ('mechanic', models.CharField(max_length=100)),
            ],
            options={
                'unique_together': {('gear_ID', 'weapon_name')},
            },
        ),
        migrations.CreateModel(
            name='Haven',
            fields=[
                ('haven_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Heat',
            fields=[
                ('heat_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('heat_description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Improvements',
            fields=[
                ('improvement_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('char_class', models.CharField(max_length=20)),
                ('text_improvement', models.CharField(max_length=20)),
                ('charm_modifier', models.IntegerField()),
                ('cool_modifier', models.IntegerField()),
                ('sharp_modifier', models.IntegerField()),
                ('tough_modifier', models.IntegerField()),
                ('weird_modifier', models.IntegerField()),
            ],
            options={
                'unique_together': {('improvement_ID', 'char_class')},
            },
        ),
        migrations.CreateModel(
            name='Lost',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('who', models.BooleanField()),
                ('what', models.BooleanField()),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Moves',
            fields=[
                ('move_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('char_type', models.CharField(max_length=20)),
                ('move_name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=1000)),
                ('default', models.BooleanField()),
                ('mechanics', models.CharField(max_length=100)),
            ],
            options={
                'unique_together': {('move_ID', 'char_type')},
            },
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('rating_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('char_class', models.CharField(max_length=20)),
                ('charm_modifier', models.IntegerField()),
                ('cool_modifier', models.IntegerField()),
                ('sharp_modifier', models.IntegerField()),
                ('tough_modifier', models.IntegerField()),
                ('weird_modifier', models.IntegerField()),
            ],
            options={
                'unique_together': {('rating_ID', 'char_class')},
            },
        ),
        migrations.CreateModel(
            name='Sect',
            fields=[
                ('sect_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('good', models.BooleanField()),
                ('bad', models.BooleanField()),
                ('sect_tag', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Spells',
            fields=[
                ('spell_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('base', models.BooleanField()),
                ('effect', models.BooleanField()),
                ('spell_name', models.CharField(max_length=20)),
                ('spell_description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Underworld',
            fields=[
                ('underworld_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('underworld_description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.RemoveField(
            model_name='game',
            name='access_key',
        ),
        migrations.RemoveField(
            model_name='game',
            name='id',
        ),
        migrations.AddField(
            model_name='game',
            name='game_ID',
            field=models.CharField(default=2, max_length=4, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CharacterSheet',
        ),
    ]
