# Generated by Django 2.2 on 2019-04-08 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='last_run_date',
        ),
    ]
