# Generated by Django 2.2 on 2019-04-09 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GameUser',
            new_name='LinkHunters',
        ),
    ]
