# Generated by Django 2.2 on 2019-04-09 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20190409_0358'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LinkHunters',
            new_name='LinkHunter',
        ),
    ]
