# Generated by Django 2.2 on 2019-04-08 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_remove_game_last_run_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='keeper',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
