# Generated by Django 2.2 on 2019-04-08 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_game_keeper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedgear',
            name='gear_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Gear'),
        ),
        migrations.AlterUniqueTogether(
            name='gear',
            unique_together=set(),
        ),
    ]
