# Generated by Django 2.2 on 2019-04-09 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20190409_0402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='game',
            name='user_ID',
            field=models.IntegerField(),
        ),
    ]
