# Generated by Django 2.2 on 2019-04-08 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20190408_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedgear',
            name='char_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.CharacterClasses'),
        ),
    ]
