# Generated by Django 2.2 on 2019-04-09 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20190408_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignedgear',
            name='gear_ID',
        ),
        migrations.AddField(
            model_name='assignedgear',
            name='gear_ID',
            field=models.ManyToManyField(to='game.Gear'),
        ),
    ]
