# Generated by Django 2.2 on 2019-04-09 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_auto_20190408_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignedgear',
            name='gear_ID',
        ),
        migrations.AddField(
            model_name='assignedgear',
            name='gear_ID',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='game.Gear'),
            preserve_default=False,
        ),
    ]
